# Generated by Django 4.2 on 2024-08-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_link', models.CharField(max_length=900, unique=True)),
                ('identifier', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
    ]
